### ISSUE TITLE
Action Mailer Rendering In Command Line, Will Not Send To Mail Servers

### ISSUE THREAD

**Issue by ambethoney** [godot-dads/wdi_admissions_app#7]
Hi PJ,

I'm working on getting action mailers to work! At this point, I have it working so that when a new student creates an account, an automatic "welcome" email is sent. In my command line, it shows the message, and confirms that it was sent, however when I check my email account, there is no email. Please help! Thanks :)

**Comment by phlco** [comment]
@ambethoney If you want to assign this to PJ you need to click on "Assign" on the right hand side!

**Comment by ambethoney** [comment]
@phlco he's not on the dropdown menu. If you or @vanderhoop are available, that works, too!

**Comment by phlco** [comment]
Then assign one of us! Make us feel wanted!

**Comment by ambethoney** [comment]
@phlco i assigned you! and we've got megan at 12.

**Comment by danadflip** [comment]
@phlco 


![](http://38.media.tumblr.com/409c1867f51a625386419af7b8d416cc/tumblr_n9srf9JBPA1rhuccro1_500.gif)

**Comment by phlco** [comment]
@ambethoney @danadflip Don't worry guys we're looking into it. How did you configure everything?

**Comment by phlco** [comment]
First I'd recommend changing some settings in your development environment to get more information about what's going on.

Take a look at  `config/environments/development.rb`

```
# config/environments/development.rb
 # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false
```

Change that to get a better idea of what errors are happening.

**Comment by ambethoney** [comment]
great, thanks!

**Comment by phlco** [comment]
What's the status of this? What errors are you receiving?

**Comment by ambethoney** [comment]
I'm receiving this error:

Connection refused - connect(2) for "localhost" port 25

I've moved on to work on something else for a while, but I understand that I need to do some research on connecting to different ports. (ugh.) Any advice and/or resources you would suggest I read?

**Comment by phlco** [comment]
Try signing up for [MandrillApp](https://mandrill.com/signup/?_ga=1.159082362.1345645400.1424375598) to send out transaction emails. The free tier allows 12k emails a month.

You'll want to configure your `config/environments/development.rb` with the following

```
  config.action_mailer.perform_deliveries = true
  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.smtp_settings = {
    address:              "smtp.mandrillapp.com",
    port:                 25, # ports 587 and 2525 are also supported with STARTTLS
    enable_starttls_auto: true, # detects and uses STARTTLS
    user_name:            ENV['mandrill_username'],
    password:             ENV['mandrill_api_key'], # SMTP password is any valid API key
    authentication:       'login', # Mandrill supports 'plain' or 'login'
    domain:               'localhost:3000', # your domain to identify your server when connecting
  }
```

**Comment by ambethoney** [comment]
Hi Phil,

So Action Mailer now runs with the Mail gem. I've configured my environment/development file according to the doc, but I'm still getting the same error:

```Connection refused - connect(2) for "localhost" port 25```

This is how I've configured it:

```config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
  address:              'smtp.gmail.com',
  port:                 25,
  domain:               'localhost:3000',
  user_name:            'ambethoney',
  password:             'xxxxxx',
  authentication:       'plain',
  enable_starttls_auto: true  }```


I'm not sure why it's unable to connect to my port!

**Comment by phlco** [comment]
Please see the above comment that explicitly tells you how to set it up and have it working :)
