### ISSUE TITLE
Inexplicable appearance of "admissions" directory within your "app" directory

### ISSUE THREAD

**Issue by vanderhoop** [godot-dads/wdi_admissions_app#9]
You have an "admissions" directory within "app". Seems like there's just a bunch of views in there, which is confusing. What's going on, guys?

**Comment by CentroDL** [comment]
![nothing](http://media.giphy.com/media/GNGBfs76E3mGk/giphy.gif)
Nothing! Nothing! YOU ONLY SEE AIR..
